export { Beaver } from './Beaver';
export { Bear } from './Bear';
export { Fox } from './Fox';
export { Owl } from './Owl';
export { Rabbit } from './Rabbit';
export { Squirrel } from './Squirrel';
export { Chipmunk } from './Chipmunk';
export { Woodpecker } from './Woodpecker';
export { Mouse } from './Mouse';
